services:
  db:
    image: mysql:8.0
    container_name: notatweb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notatweb
      MYSQL_USER: notatweb_user
      MYSQL_PASSWORD: notatweb_password
    volumes:
      - notat-vol:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - notat-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./app
    container_name: notatweb_api
    restart: always
    env_file:
      - ./app/.env
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=notatweb
      - MYSQL_USER=notatweb_user
      - MYSQL_PASSWORD=notatweb_password
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - notat-net

  frontweb:
    build: ./frontweb
    container_name: notatweb_frontweb
    restart: always
    networks:
      - notat-net

  nginx:
    image: nginx:alpine
    container_name: notatweb_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - api
      - frontweb
    networks:
      - notat-net

networks:
  notat-net:
    driver: bridge

volumes:
  notat-vol:
